# Generated by Django 5.1.7 on 2025-05-12 08:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorsCatalog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('author_surname', models.TextField()),
                ('author_name', models.TextField()),
                ('author_patronymic', models.TextField()),
            ],
            options={
                'db_table': 'Authors_catalog',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='BooksCatalog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('index', models.TextField(unique=True)),
                ('authors_mark', models.TextField()),
                ('title', models.TextField()),
                ('place_publication', models.TextField()),
                ('information_publication', models.TextField()),
                ('volume', models.IntegerField()),
                ('quantity_total', models.IntegerField()),
                ('quantity_remaining', models.IntegerField()),
                ('cover', models.ImageField(blank=True, null=True, upload_to='covers/')),
                ('date_publication', models.TextField()),
            ],
            options={
                'db_table': 'Books_catalog',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ReadersCatalog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('surname', models.TextField()),
                ('name', models.TextField()),
                ('patronymic', models.TextField(blank=True, null=True)),
                ('birthday', models.DateField()),
                ('education', models.TextField()),
                ('profession', models.TextField(blank=True, null=True)),
                ('educational_inst', models.TextField(blank=True, null=True)),
                ('city', models.TextField()),
                ('street', models.TextField()),
                ('house', models.IntegerField()),
                ('building_house', models.TextField(blank=True, null=True)),
                ('flat', models.IntegerField(blank=True, null=True)),
                ('passport_series', models.IntegerField()),
                ('passport_number', models.IntegerField()),
                ('issued_by_whom', models.TextField()),
                ('date_issue', models.DateField()),
                ('consists_of', models.DateField()),
                ('re_registration', models.DateField(blank=True, null=True)),
                ('phone', models.TextField()),
                ('login', models.TextField(blank=True, null=True)),
                ('password', models.TextField(blank=True, null=True)),
                ('mail', models.TextField(blank=True, null=True)),
                ('admin', models.BooleanField()),
            ],
            options={
                'db_table': 'Readers_catalog',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='OrderCatalog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('author_surname', models.TextField()),
                ('author_name', models.TextField(blank=True, null=True)),
                ('author_patronymic', models.TextField(blank=True, null=True)),
                ('quantyti', models.IntegerField()),
                ('date_publication', models.TextField(blank=True, null=True)),
                ('reader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='work_table.readerscatalog')),
            ],
            options={
                'db_table': 'Order_catalog',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('comment', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='work_table.readerscatalog')),
            ],
            options={
                'db_table': 'Comments',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='BookingCatalog',
            fields=[
                ('quantity', models.IntegerField()),
                ('date_issue', models.DateField()),
                ('date_return', models.DateField()),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('issued', models.BooleanField()),
                ('returned', models.BooleanField()),
                ('index', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='work_table.bookscatalog')),
                ('reader', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='work_table.readerscatalog')),
            ],
            options={
                'db_table': 'Booking_catalog',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='AuthorsBooks',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='work_table.authorscatalog')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='work_table.bookscatalog')),
            ],
            options={
                'db_table': 'Authors_Books',
                'managed': True,
                'unique_together': {('author', 'book')},
            },
        ),
    ]
