# Generated by Django 5.1.7 on 2025-05-12 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_table', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readerscatalog',
            name='login',
            field=models.TextField(default='temp_login', unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='readerscatalog',
            name='mail',
            field=models.TextField(default='temp_login'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='readerscatalog',
            name='password',
            field=models.TextField(default='temp'),
            preserve_default=False,
        ),
    ]
