# Generated by Django 5.1.7 on 2025-05-12 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_table', '0002_alter_readerscatalog_login_alter_readerscatalog_mail_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='readerscatalog',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
