# Generated by Django 5.1.7 on 2025-05-14 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work_table', '0003_readerscatalog_is_active'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='readerscatalog',
            unique_together={('passport_series', 'passport_number')},
        ),
    ]
