# Generated by Django 5.1.7 on 2025-05-14 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_table', '0004_alter_readerscatalog_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authorscatalog',
            name='author_patronymic',
            field=models.TextField(blank=True, null=True),
        ),
    ]
