# Generated by Django 5.1.7 on 2025-05-18 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_table', '0005_alter_authorscatalog_author_patronymic'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comments',
            options={'managed': True, 'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='comments',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2025-05-05'),
            preserve_default=False,
        ),
    ]
