# Generated by Django 5.1.7 on 2025-05-27 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work_table', '0006_alter_comments_options_comments_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookingcatalog',
            options={'managed': True, 'ordering': ['-date_issue']},
        ),
    ]
