# Generated by Django 5.1.7 on 2025-05-29 13:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_table', '0007_alter_bookingcatalog_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenresCatalog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(unique=True)),
            ],
            options={
                'db_table': 'Genres_catalog',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='BooksGenres',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='work_table.bookscatalog')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='work_table.genrescatalog')),
            ],
            options={
                'db_table': 'Books_Genres',
                'managed': True,
                'unique_together': {('book', 'genre')},
            },
        ),
        migrations.AddField(
            model_name='bookscatalog',
            name='genres',
            field=models.ManyToManyField(related_name='books', through='work_table.BooksGenres', to='work_table.genrescatalog'),
        ),
    ]
