# Generated by Django 5.1.7 on 2025-06-01 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_table', '0008_genrescatalog_booksgenres_bookscatalog_genres'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordercatalog',
            name='confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='bookingcatalog',
            name='issued',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='bookingcatalog',
            name='returned',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterUniqueTogether(
            name='bookingcatalog',
            unique_together={('index', 'reader')},
        ),
    ]
