# Generated by Django 5.1.7 on 2025-06-04 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work_table', '0009_ordercatalog_confirmed_alter_bookingcatalog_issued_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ordercatalog',
            unique_together={('title', 'author_surname')},
        ),
    ]
