# Generated by Django 5.1.7 on 2025-06-05 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work_table', '0010_alter_ordercatalog_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ordercatalog',
            unique_together={('title', 'reader')},
        ),
    ]
